// Mock data for products
export const productsData = [
    {
      id: "PROD-001",
      name: "Portland Cement 50kg",
      category: "Cement",
      sku: "CEM-PORT-50",
      stock: 450,
      lowStockThreshold: 100,
      price: 12.50,
      supplier: "CemCorp Industries",
      lastRestocked: "2024-01-15",
      status: "active",
      branch: "Main Warehouse",
      description: "High-quality Portland cement suitable for all construction projects. Meets ASTM standards.",
      dimensions: "60cm x 40cm x 15cm",
      weight: "50kg",
    },
    {
      id: "PROD-002", 
      name: "Steel Rebar 12mm x 6m",
      category: "Steel",
      sku: "STL-RBR-12",
      stock: 25,
      lowStockThreshold: 50,
      price: 45.80,
      supplier: "SteelMax Ltd",
      lastRestocked: "2024-01-10",
      status: "low_stock",
      branch: "Steel Yard",
      description: "Reinforcement steel bars for concrete structures. Grade 60 steel.",
      dimensions: "12mm diameter x 6m length",
      weight: "6.7kg",
    },
    {
      id: "PROD-003",
      name: "Concrete Blocks 200x200x400",
      category: "Blocks",
      sku: "BLK-CON-200",
      stock: 1200,
      lowStockThreshold: 200,
      price: 2.75,
      supplier: "BlockCraft Co",
      lastRestocked: "2024-01-12",
      status: "active",
      branch: "Block Yard",
      description: "Standard concrete masonry blocks for construction projects.",
      dimensions: "200x200x400mm",
      weight: "18kg",
    },
    {
      id: "PROD-004",
      name: "Crushed Stone Aggregate",
      category: "Aggregates",
      sku: "AGG-CRUS-20",
      stock: 0,
      lowStockThreshold: 10,
      price: 35.00,
      supplier: "RockQuarry Inc",
      lastRestocked: "2023-12-28",
      status: "no_stock",
      branch: "Aggregate Yard",
      description: "20mm crushed stone aggregate for concrete mixing and road construction.",
      dimensions: "Bulk material - per ton",
      weight: "1000kg per ton",
    },
    {
      id: "PROD-005",
      name: "Roof Tiles - Clay Red",
      category: "Roofing",
      sku: "RF-CLY-RED",
      stock: 750,
      lowStockThreshold: 100,
      price: 1.85,
      supplier: "RoofMaster Ltd",
      lastRestocked: "2024-01-08",
      status: "active", 
      branch: "Roofing Center",
      description: "Traditional clay roof tiles in red color. Weather resistant and durable.",
      dimensions: "420mm x 330mm x 15mm",
      weight: "2.8kg",
    },
  ];

// Mock data for orders
export const ordersData = [
  {
    id: "ORD-2024-001",
    customerName: "BuildRight Construction",
    customerEmail: "orders@buildright.com",
    orderDate: "2025-09-15",
    deliveryDate: "2025-09-18",
    status: "shipped",
    total: 1245.80,
    items: 5,
    branch: "Main Warehouse",
    paymentStatus: "paid",
    shippingAddress: "123 Construction Ave, BuildCity, BC 12345",
    orderItems: [
      { product: "Portland Cement 50kg", quantity: 10, unitPrice: 12.50 },
      { product: "Steel Rebar 12mm x 6m", quantity: 20, unitPrice: 45.80 },
      { product: "Concrete Blocks", quantity: 50, unitPrice: 2.75 },
    ],
  },
  {
    id: "ORD-2024-002",
    customerName: "Metro Housing Project",
    customerEmail: "procurement@metrohousing.com", 
    orderDate: "2025-09-16",
    deliveryDate: "2025-09-19",
    status: "pending",
    total: 3567.50,
    items: 12,
    branch: "Steel Yard",
    paymentStatus: "pending",
    shippingAddress: "456 Housing Complex Rd, Metro City, MC 67890",
    orderItems: [
      { product: "Steel Rebar 12mm x 6m", quantity: 50, unitPrice: 45.80 },
      { product: "Crushed Stone Aggregate", quantity: 5, unitPrice: 35.00 },
    ],
  },
  {
    id: "ORD-2024-003",
    customerName: "Residential Builders Ltd",
    customerEmail: "supply@resbuilders.com",
    orderDate: "2025-09-14",
    deliveryDate: "2025-09-17", 
    status: "completed",
    total: 892.25,
    items: 8,
    branch: "Block Yard",
    paymentStatus: "paid",
    shippingAddress: "789 Residential St, Suburb City, SC 54321",
    orderItems: [
      { product: "Concrete Blocks", quantity: 200, unitPrice: 2.75 },
      { product: "Roof Tiles - Clay Red", quantity: 150, unitPrice: 1.85 },
    ],
  },
  {
    id: "ORD-2024-004",
    customerName: "Highway Construction Co",
    customerEmail: "materials@highwayco.com",
    orderDate: "2025-09-13",
    deliveryDate: "2025-09-20",
    status: "cancelled",
    total: 2100.00,
    items: 3,
    branch: "Aggregate Yard", 
    paymentStatus: "refunded",
    shippingAddress: "Highway 101 Project Site, Road City, RC 98765",
    orderItems: [
      { product: "Crushed Stone Aggregate", quantity: 60, unitPrice: 35.00 },
    ],
  },
];

// Mock data for branches
export const branchesData = [
  {
    id: "BR-001",
    name: "Main Warehouse",
    address: "1234 Industrial Blvd, Construction City, CC 12345",
    manager: "John Smith",
    phone: "+1 (555) 123-4567",
    email: "main@constructpro.com",
    employees: 25,
    status: "active",
    monthlyRevenue: 125000,
    yearlyRevenue: 1400000,
    openingHours: "6:00 AM - 6:00 PM",
    specialties: ["General Construction", "Cement", "Steel"],
    warehouseSize: "50,000 sq ft",
    established: "2018-03-15",
  },
  {
    id: "BR-002", 
    name: "Steel Yard",
    address: "5678 Metal Works Dr, Steel Town, ST 23456",
    manager: "Sarah Johnson",
    phone: "+1 (555) 234-5678",
    email: "steel@constructpro.com", 
    employees: 18,
    status: "active",
    monthlyRevenue: 89000,
    yearlyRevenue: 980000,
    openingHours: "7:00 AM - 5:00 PM",
    specialties: ["Steel Products", "Rebar", "Metal Fabrication"],
    warehouseSize: "35,000 sq ft",
    established: "2019-06-10",
  },
  {
    id: "BR-003",
    name: "Block Yard", 
    address: "9012 Masonry Ave, Block City, BC 34567",
    manager: "Mike Williams", 
    phone: "+1 (555) 345-6789",
    email: "blocks@constructpro.com",
    employees: 12,
    status: "active",
    monthlyRevenue: 67000,
    yearlyRevenue: 720000,
    openingHours: "6:30 AM - 5:30 PM", 
    specialties: ["Concrete Blocks", "Masonry", "Precast"],
    warehouseSize: "25,000 sq ft",
    established: "2020-01-20",
  },
  {
    id: "BR-004",
    name: "Roofing Center",
    address: "3456 Roof Top Lane, Sky City, SK 45678",
    manager: "Lisa Davis",
    phone: "+1 (555) 456-7890", 
    email: "roofing@constructpro.com",
    employees: 8,
    status: "active",
    monthlyRevenue: 45000,
    yearlyRevenue: 520000,
    openingHours: "7:00 AM - 4:00 PM",
    specialties: ["Roofing Materials", "Tiles", "Insulation"],
    warehouseSize: "15,000 sq ft",
    established: "2021-09-05",
  },
  {
    id: "BR-005",
    name: "Aggregate Yard",
    address: "7890 Quarry Road, Stone Valley, SV 56789",
    manager: "Robert Brown",
    phone: "+1 (555) 567-8901",
    email: "aggregate@constructpro.com",
    employees: 15,
    status: "maintenance",
    monthlyRevenue: 32000,
    yearlyRevenue: 410000,
    openingHours: "6:00 AM - 6:00 PM",
    specialties: ["Aggregates", "Sand", "Gravel"],
    warehouseSize: "60,000 sq ft",
    established: "2017-11-12",
  },
];

// Dummy employee data
export const employeeData = [
  {
    id: "EMP001",
    name: "Owino Dalienst",
    email: "owino@corban.com",
    phone: "0710407873",
    role: "Branch Manager",
    branch: "Downtown Warehouse",
    avatarUrl: null,
  },
  {
    id: "EMP002", 
    name: "Patricia Owino",
    email: "patricia@gmail.com",
    phone: "0702405552",
    role: "Sales Representative",
    branch: "North Side Depot",
    avatarUrl: null,
  },
  {
    id: "EMP003",
    name: "Ligogo Senior",
    email: "ligogo@gmail.com", 
    phone: "0790430603",
    role: "Inventory Specialist",
    branch: "Downtown Warehouse",
    avatarUrl: null,
  },
  {
    id: "EMP004",
    name: "First Uncle",
    email: "firstunc@gmail.com",
    phone: "0711204596",
    role: "Delivery Coordinator",
    branch: "South District Center",
    avatarUrl: null,
  },
  {
    id: "EMP005",
    name: "Second uncle",
    email: "secondunc@gmail.com",
    phone: "0789640203",
    role: "Quality Inspector",
    branch: "North Side Depot",
    avatarUrl: null,
  },
];

// Dummy data for quotations
export const quotations = [
  {
    id: "Q001",
    contractorName: "BuildCorp Ltd",
    projectName: "Downtown Office Complex",
    items: "Concrete, Steel Beams, Insulation",
    totalAmount: 125000,
    status: "sent",
    createdDate: "2024-01-15",
    sentDate: "2024-01-16",
    validUntil: "2024-02-16",
    type: "quotation"
  },
  {
    id: "Q002", 
    contractorName: "Metro Builders",
    projectName: "Residential Tower Phase 2",
    items: "Drywall, Electrical Components, Plumbing",
    totalAmount: 87500,
    status: "draft",
    createdDate: "2024-01-18",
    sentDate: null,
    validUntil: "2024-02-18",
    type: "quotation"
  },
  {
    id: "R001",
    contractorName: "Urban Development Co", 
    projectName: "Shopping Mall Renovation",
    items: "Windows, Doors, Flooring Materials",
    totalAmount: null,
    status: "pending_quote",
    createdDate: "2024-01-20",
    sentDate: null,
    validUntil: null,
    type: "request"
  },
  {
    id: "Q003",
    contractorName: "Skyline Construction",
    projectName: "Industrial Warehouse",
    items: "Metal Roofing, Structural Steel, Concrete",
    totalAmount: 235000,
    status: "sent",
    createdDate: "2024-01-12",
    sentDate: "2024-01-14",
    validUntil: "2024-02-14",
    type: "quotation"
  },
  {
    id: "R002",
    contractorName: "Heritage Builders",
    projectName: "Historic Building Restoration", 
    items: "Specialty Brick, Restoration Materials, Stone",
    totalAmount: null,
    status: "pending_quote",
    createdDate: "2024-01-22",
    sentDate: null,
    validUntil: null,
    type: "request"
  }
];

// Dummy quotation data
export const quotationData = {
  id: "Q001",
  contractorName: "BuildCorp Ltd",
  contractorEmail: "procurement@buildcorp.com",
  contractorPhone: "+1 (555) 123-4567",
  projectName: "Downtown Office Complex",
  projectAddress: "123 Business District, Metro City",
  status: "draft",
  createdDate: "2024-01-15",
  validUntil: "2024-02-16",
  items: [
    {
      id: 1,
      description: "High-grade concrete (40 MPa)",
      quantity: 500,
      unit: "cubic meters",
      unitPrice: 120,
      total: 60000
    },
    {
      id: 2,
      description: "Structural steel beams (Grade A)",
      quantity: 50,
      unit: "tons",
      unitPrice: 800,
      total: 40000
    },
    {
      id: 3,
      description: "Thermal insulation materials",
      quantity: 200,
      unit: "square meters",
      unitPrice: 125,
      total: 25000
    }
  ],
  subtotal: 125000,
  tax: 12500,
  total: 137500,
  notes: "All materials meet construction standards. Delivery within 2 weeks of order confirmation. Installation support available.",
  terms: "Payment due within 30 days. 50% deposit required upon acceptance."
};
